### ISSUE TITLE
关于“套壳”一词

### ISSUE THREAD

**Issue by nobodxbodon** [louisyoungx/zpy-lab#1]
在此词实际上已被滥用的当下，个人认为只需遵守开源协议即可，无需特意说明。
在什么是“壳”，自研成分占多少、设计多么独特才不算“套壳”都并无公论的情况下，讨论“是否套壳”往往沦为口水战。

**Comment by louisyoungx** [comment]
没事🤣被套壳那人跟他开玩笑的



---原始邮件---
发件人: "吴烜 xuan ***@***.***&gt;
发送时间: 2021年12月12日(周日) 中午12:41
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [louisyoungx/zpy-lab] 关于“套壳”一词 (Issue #1)




 
在此词实际上已被滥用的当下，个人认为只需遵守开源协议即可，无需特意说明。
 在什么是“壳”，自研成分占多少、设计多么独特才不算“套壳”都并无公论的情况下，讨论“是否套壳”往往沦为口水战。
